TERCEIRA LISTA DE EXERCÍCIOS - PANDAS

In [3]:
import pandas as pd

QUESTÃO 1 - Utilizando groupby(), calcule o total de vendas para cada produto.

In [8]:
df = pd.DataFrame({
    "Produto": ["Notebook","Notebook","Mouse","Mouse"],
    "Vendas": [10,15,20,25]
})

vendas_produtos = df.groupby("Produto")["Vendas"].agg("sum")
print("Vendas por produto: ")
display(vendas_produtos)

Vendas por produto:

Produto
Mouse       45
Notebook    25
Name: Vendas, dtype: int64

QUESTÃO 2 - Calcule a média de vendas por cidade.

In [9]:
df = pd.DataFrame({
    "Cidade": ["SP","SP","RJ","RJ"],
    "Vendas": [10,20,30,40]
})

media_cidades = df.groupby("Cidade")["Vendas"].agg("mean")
print("Media de vendas por cidade: ")
display(media_cidades)

Media de vendas por cidade:

Cidade
RJ    35.0
SP    15.0
Name: Vendas, dtype: float64

QUESTÃO 3 - Conte quantas vezes cada produto aparece no DataFrame.

In [12]:
df = pd.DataFrame({
    "Produto": ["Notebook","Mouse","Mouse","Teclado","Notebook"]
})

contagem_produtos = df["Produto"].value_counts()
print("Contagem dos produtos: ")
display(contagem_produtos)

Contagem dos produtos:

Produto
Notebook    2
Mouse       2
Teclado     1
Name: count, dtype: int64

QUESTÃO 4 - Agrupe os dados por Produto e Cidade e calcule a soma das vendas.

In [14]:
df = pd.DataFrame({
    "Produto": ["Notebook","Notebook","Mouse","Mouse"],
    "Cidade": ["SP","RJ","SP","RJ"],
    "Vendas": [10,15,20,25]
})

print("Soma das vendas por produto e cidade:")
display(df.groupby(["Produto","Cidade"]).agg("sum"))

Soma das vendas por produto e cidade:

                 Vendas
Produto  Cidade
Mouse    RJ          25
         SP          20
Notebook RJ          15
         SP          10

QUESTÃO 5 - Descubra qual foi a maior venda registrada para cada produto.

In [16]:
df = pd.DataFrame({
    "Produto": ["Notebook","Notebook","Mouse","Mouse"],
    "Vendas": [10,50,20,25]
})

maiores_vendas = df.groupby("Produto")["Vendas"].agg("max")
print("Maior venda de cada produto:")
display(maiores_vendas)

Maior venda de cada produto:

Produto
Mouse       25
Notebook    50
Name: Vendas, dtype: int64

QUESTÃO 6 - Calcule o preço médio de cada produto.

In [19]:
df = pd.DataFrame({
    "Produto": ["Notebook","Notebook","Mouse","Mouse"],
    "Preco": [3000,3200,50,55]
})

precos_medios = df.groupby("Produto")["Preco"].agg("mean")
print("Preço médio por produto:")
display(precos_medios)

Preço médio por produto:

Produto
Mouse         52.5
Notebook    3100.0
Name: Preco, dtype: float64

QUESTÃO 7 - Calcule o total de clientes por cidade.

In [21]:
df = pd.DataFrame({
    "Cidade": ["SP","RJ","SP","BH","RJ"],
    "Clientes": [100,150,200,80,120]
})

clientes_por_cidade = df.groupby("Cidade")["Clientes"].agg("sum")
print("Total de clientes por cidade:")
display(clientes_por_cidade)

Total de clientes por cidade:

Cidade
BH     80
RJ    270
SP    300
Name: Clientes, dtype: int64

QUESTÃO 8 - Calcule o salário médio por departamento.

In [22]:
df = pd.DataFrame({
    "Departamento": ["TI","TI","RH","RH","Financeiro"],
    "Salario": [5000,6000,4000,4200,7000]
})

salarios_medios = df.groupby("Departamento")["Salario"].agg("mean")
print("Salário médio por departamento:")
display(salarios_medios)

Salário médio por departamento:

Departamento
Financeiro    7000.0
RH            4100.0
TI            5500.0
Name: Salario, dtype: float64

QUESTÃO 9 - Calcule o total de itens por categoria.

In [23]:
df = pd.DataFrame({
    "Categoria": ["Eletronico","Eletronico","Movel","Movel"],
    "Quantidade": [5,10,3,7]
})

itens_por_categoria = df.groupby("Categoria")["Quantidade"].agg("sum")
print("Total de itens por categoria: ")
display(itens_por_categoria)

Total de itens por categoria:

Categoria
Eletronico    15
Movel         10
Name: Quantidade, dtype: int64

QUESTÃO 10 - Calcule o total de vendas por produto e ano.

In [24]:
df = pd.DataFrame({
    "Produto": ["Notebook","Notebook","Mouse","Mouse"],
    "Ano": [2023,2024,2023,2024],
    "Vendas": [10,15,20,25]
})

vendas_por_produto_e_ano = df.groupby(["Produto","Ano"]).agg("sum")
print("Total de vendas por produto e ano:")
display(vendas_por_produto_e_ano)

Total de vendas por produto e ano:

               Vendas
Produto  Ano
Mouse    2023      20
         2024      25
Notebook 2023      10
         2024      15

QUESTÃO 11 - Calcule a média de notas por aluno.

In [25]:
df = pd.DataFrame({
    "Aluno": ["Ana","Ana","Joao","Joao"],
    "Nota": [7,9,6,8]
})

medias = df.groupby("Aluno")["Nota"].agg("mean")
print("Média de notas de cada aluno:")
display(medias)

Média de notas de cada aluno:

Aluno
Ana     8.0
Joao    7.0
Name: Nota, dtype: float64

QUESTÃO 12 - Calcule a temperatura máxima por cidade.

In [27]:
df = pd.DataFrame({
    "Cidade": ["SP","SP","RJ","RJ"],
    "Temperatura": [30,32,28,27]
})

temperaturas_maximas = df.groupby("Cidade")["Temperatura"].agg("max")
print("Temperatura máxima por cidade:")
display(temperaturas_maximas)

Temperatura máxima por cidade:

Cidade
RJ    28
SP    32
Name: Temperatura, dtype: int64

QUESTÃO 13 - Calcule a menor quantidade vendida por produto.

In [28]:
df = pd.DataFrame({
"Produto": ["Notebook","Notebook","Mouse","Mouse"],
"Quantidade": [5,2,10,8]
})

menores_quantidades_vendidas = df.groupby("Produto")["Quantidade"].agg("min")
print("Menor quantidade vendida por produto:")
print(menores_quantidades_vendidas)

Menor quantidade vendida por produto:
Produto
Mouse       8
Notebook    2
Name: Quantidade, dtype: int64

QUESTÃO 14 - Calcule o preço médio e a soma da quantidade por categoria.

In [54]:
df = pd.DataFrame({
    "Categoria": ["Eletronico","Eletronico","Movel","Movel"],
    "Preco": [1000,1200,500,700],
    "Quantidade": [2,3,1,4]
})

df14 = df.groupby("Categoria").agg({
    "Preco": "mean",
    "Quantidade": "sum"
})
df14.rename(columns={"Preco":"Preco medio"}, inplace=True)
print("Preço médio e soma das quantidades por categoria:")
display(df14)

Preço médio e soma das quantidades por categoria:

            Preco medio  Quantidade
Categoria
Eletronico       1100.0           5
Movel             600.0           5

QUESTÃO 15 - Agrupe os dados por região e ordene o resultado pelas maiores vendas.

In [31]:
df = pd.DataFrame({
    "Regiao": ["Norte","Sul","Norte","Sudeste","Sul"],
    "Vendas": [100,200,150,300,250]
})

df_por_regiao = df.groupby("Regiao")["Vendas"].agg("sum")
df_por_regiao = df_por_regiao.sort_values(ascending=False)
print("Vendas por região(da maior para a menor):")
display(df_por_regiao)

Vendas por região(da maior para a menor):

Regiao
Sul        450
Sudeste    300
Norte      250
Name: Vendas, dtype: int64